### ISSUE TITLE
Beginner question about VibFreqs and IRIntensity

### ISSUE THREAD

**Issue by sofroniewn** [pstjohn/bde#4]
Hello, awesome project here!

I'm a complete beginner when it comes to quantum computational chemistry, but I'm interested in predicting spectra of organic molecules and so was excited come across your [paper](https://www.nature.com/articles/s41597-020-00588-x) and this project. I was able to successfully download the data from [figshare](https://springernature.figshare.com/articles/dataset/Chemical_table_file_of_optimized_structures_/12158646) and load it as a dataframe following the first 5 cells of your [notebook](https://github.com/pstjohn/bde/blob/master/doc/sdf_load_demonstration_with_rdkit.ipynb). When I look at `IRIntensity` and `VibFreqs` though it seems like the length of these vectors varies for each molecule and in ways that I don't understand. Naively I was expecting `VibFreqs` to range over some fixed interval (and be the same for every molecule!) and then `IRIntensity` report the IR absorption at each frequency. I was hoping to make spectral plots like the following 

![image](https://user-images.githubusercontent.com/6531703/150665891-3e8eee72-c996-4081-98f6-57322d57ece3.png)

but it is now clear to me that I don't really understand what information is in `VibFreqs` and `IRIntensity`. Should I take the unspecified values to be zero and then do some smoothing? Or am I way off with what these data represent. Apologies if that is a really dumb question. If you could you give me any pointers on how I could make plots of the IR absorption spectra though that would be great. Maybe also any additional information on how you used Gaussian to predict the `IRIntensity` would be helpful too.

Thanks so much!!

**Comment by bobbypaton** [comment]
Hi

Vibreqs is a list of the  harmonic vibrational normal modes in cm-1. For a given molecule the length is equal to 3N-6 (or 3N-5 for linear molecules) where N is the number of atoms. These are obtained from a calculation of the mass-weighted Hessian matrix of second energy derivatives which has dimensions of 3N - the normal mode frequencies are the non-zero eigenvalues after diagonalization.

IRIntensity is a list of equal length to Vibfreqs. This comes from the calculated dipole derivative for each normal mode, which governs its absorbance.

To convert these data to a realistic looking spectrum you could use some lorentzians to simulate line width at each normal mode frequency, add them together and then plot.

have a look at programs like GaussSum...


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Nicholas Sofroniew ***@***.***>
Sent: Saturday, January 22, 2022 10:16:56 PM
To: pstjohn/bde ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pstjohn/bde] Beginner question about VibFreqs and IRIntensity (Issue #4)


** Caution: EXTERNAL Sender **

Hello, awesome project here!

I'm a complete beginner when it comes to quantum computational chemistry, but I'm interested in predicting spectra of organic molecules and so was excited come across your paper<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Farticles%2Fs41597-020-00588-x&data=04%7C01%7Crobert.paton%40colostate.edu%7C6701458a4f274ee3983a08d9de2f9408%7Cafb58802ff7a4bb1ab21367ff2ecfc8b%7C0%7C0%7C637785118204070573%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OoDRppoNX81178LkVYZAbVgdcDVPUtowFjwkDIaGOHM%3D&reserved=0> and this project. I was able to successfully download the data from [figshare(https://springernature.figshare.com/articles/dataset/Chemical_table_file_of_optimized_structures_/12158646) and load it as a dataframe following the first 5 cells of your notebook<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpstjohn%2Fbde%2Fblob%2Fmaster%2Fdoc%2Fsdf_load_demonstration_with_rdkit.ipynb&data=04%7C01%7Crobert.paton%40colostate.edu%7C6701458a4f274ee3983a08d9de2f9408%7Cafb58802ff7a4bb1ab21367ff2ecfc8b%7C0%7C0%7C637785118204070573%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=H3gJZsRrXH5A4bGJ0MKE%2FsukzIXBbiWoLVo9nZij5Hg%3D&reserved=0>. When I look at IRIntensity and VibFreqs though it seems like the length of these vectors varies for each molecule and in ways that I don't understand. Naively I was expecting VibFreqs to range over some fixed interval (and be the same for every molecule!) and then IRIntensity report the IR absorption at each frequency. I was hoping to make spectral plots like the following

[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6531703%2F150665891-3e8eee72-c996-4081-98f6-57322d57ece3.png&data=04%7C01%7Crobert.paton%40colostate.edu%7C6701458a4f274ee3983a08d9de2f9408%7Cafb58802ff7a4bb1ab21367ff2ecfc8b%7C0%7C0%7C637785118204070573%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8yT6Wmoxzi8bKTOhwcr39H3ogUjEJKpa9nrLYSrb2TE%3D&reserved=0>

but it is now clear to me that I don't really understand what information is in VibFreqs and IRIntensity. Should I take the unspecified values to be zero and then do some smoothing? Or am I way off with what these data represent. Apologies if that is a really dumb question. If you could you give me any pointers on how I could make plots of the IR absorption spectra though that would be great. Maybe also any additional information on how you used Gaussian to predict the IRIntensity would be helpful too.

Thanks so much!!

**Comment by sofroniewn** [comment]
Perfect, that is very helpful information and makes a lot of sense!

I did find an [example](http://gausssum.sourceforge.net/Example/index.html) in the GaussSum docs that is exactly what I want so thanks very much for that, but it looks like GaussSum is more of a GUI app and doesn't support mac.

I then found some code to do the conversion inside [ASE.Vibrations.Vibrations.fold](https://wiki.fysik.dtu.dk/ase/_modules/ase/vibrations/vibrations.html#Vibrations.fold) which does the job

Here's a plot after picking some hopefully reasonable parameter values

![image](https://user-images.githubusercontent.com/6531703/150706672-b21fc14f-a11e-43f9-b90f-82f373418910.png)

Does this look roughly reasonable to you? Maybe a better question, is this an appropriate way to use the data from your database?

I'm also curious if you happen know/ can recommend the [ASE](https://wiki.fysik.dtu.dk/ase/index.html) package in general? As a complete beginner I just found it via a google search, but it looks popular.

Thanks again!!

**Comment by sofroniewn** [comment]
Also @bobbypaton totally small world, I just saw you did your PhD with Jonathan Goodman - he was my DoS at Clare and Chem supervisor in 2005 when I was a first year Nat Sci before I switching to Maths. I'm definitely digging back into the memory banks to fetch any of that Chem knowledge now :-)

**Comment by bobbypaton** [comment]
Looks good – in general the line broadening for certain groups (e.g. OH) can be much wider, depending on things like concentration or medium – but that’s hard to predict ab initio …

ASE is also great

Rob

Robert Paton | Professor | Colorado State University
http://patonlab.colostate.edu<http://patonlab.colostate.edu/>




From: Nicholas Sofroniew ***@***.***>
Date: Sunday, January 23, 2022 at 6:12 PM
To: pstjohn/bde ***@***.***>
Cc: Paton,Robert ***@***.***>, Comment ***@***.***>
Subject: Re: [pstjohn/bde] Beginner question about VibFreqs and IRIntensity (Issue #4)

** Caution: EXTERNAL Sender **

Perfect, thats is very helpful information and makes a lot of sense!

I did find an example<https://nam10.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgausssum.sourceforge.net%2FExample%2Findex.html&data=04%7C01%7Crobert.paton%40colostate.edu%7Cffdab2df8e694f02fd6d08d9ded6a129%7Cafb58802ff7a4bb1ab21367ff2ecfc8b%7C0%7C0%7C637785835678486511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4bRcC%2F8XzJGJRPng2FZ7d%2F3%2FGTwwqBR0rq2n5EDlEiU%3D&reserved=0> in the GaussSum docs that is exactly what I want so thanks very much for that, but it looks like GaussSum is more of a GUI app and doesn't support mac.

I then found some code to do the conversion inside ASE.Vibrations.Vibrations.fold<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwiki.fysik.dtu.dk%2Fase%2F_modules%2Fase%2Fvibrations%2Fvibrations.html%23Vibrations.fold&data=04%7C01%7Crobert.paton%40colostate.edu%7Cffdab2df8e694f02fd6d08d9ded6a129%7Cafb58802ff7a4bb1ab21367ff2ecfc8b%7C0%7C0%7C637785835678486511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=59m5J8Z%2Bo%2Fyl3DsTf7sV0upzJnpM2NwSGfVzLNGnny4%3D&reserved=0> which does the job

Here's a plot after picking some hopefully reasonable parameter values

[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6531703%2F150706672-b21fc14f-a11e-43f9-b90f-82f373418910.png&data=04%7C01%7Crobert.paton%40colostate.edu%7Cffdab2df8e694f02fd6d08d9ded6a129%7Cafb58802ff7a4bb1ab21367ff2ecfc8b%7C0%7C0%7C637785835678486511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=W8tGytGOvApSUE0n8csEYzhL3x7eJs2USVvgDs5ZcZY%3D&reserved=0>

Does this look roughly reasonable to you? Maybe a better question, is this an appropriate way to use the data from your database?

I'm also curious if you happen know/ can recommend the ASE<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwiki.fysik.dtu.dk%2Fase%2Findex.html&data=04%7C01%7Crobert.paton%40colostate.edu%7Cffdab2df8e694f02fd6d08d9ded6a129%7Cafb58802ff7a4bb1ab21367ff2ecfc8b%7C0%7C0%7C637785835678486511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XWdgmCwXD%2FDUnqFAjeb9ZCG5RwW6ZNvkCBsElwbPB6A%3D&reserved=0> package in general? As a complete beginner I just found it via a google search, but it looks popular.

Thanks again!!

**Comment by sofroniewn** [comment]
Great, thanks so much for all your help!! I will close this now
